add processing of not start completely

diff --git a/installed/usr/bin/fde_utils b/installed/usr/bin/fde_utils
--- a/installed/usr/bin/fde_utils
+++ b/installed/usr/bin/fde_utils
@@ -9,6 +9,7 @@ return_code_not_root=12
 return_code_stopped=13
 return_code_not_stopped=14
 return_code_not_running=15
+return_code_not_start_completely=16
 
 if [ $# -lt 1 ];then
     exit 
@@ -92,7 +93,13 @@ function apk_process() {
 			return $?
 		;;
 		"list")
-			curl http://127.0.0.1:18080/api/v1/android/apps?raw=1 -X GET 2>/dev/null 
+			code=`curl -s -o /tmp/fde_app_list  -w "%{http_code}" http://127.0.0.1:18080/api/v1/android/apps?raw=1 -X GET 2>/dev/null`
+			if [ "$code" != "200" ];then
+				echo "Error: fde is not started completely"
+				exit $return_code_not_start_completely
+			fi
+			cat /tmp/fde_app_list
+			rm /tmp/fde_app_list 2>/dev/null
 			exit 0
 		;;
 		"app_stop")
