add stop opcode

diff --git a/installed/usr/bin/fde_utils b/installed/usr/bin/fde_utils
--- a/installed/usr/bin/fde_utils
+++ b/installed/usr/bin/fde_utils
@@ -81,6 +81,14 @@ function apk_process() {
 			curl http://127.0.0.1:18080/api/v1/android/apps?raw=1 -X GET 2>/dev/null 
 			exit 0
 		;;
+		"stop")
+			if [ "$(id -u)" -ne 0 ]; then
+				echo "Error: This operation must be run as root." >&2
+				exit $return_code_not_root
+			fi
+			waydroid shell am force-stop $2 >&2
+			exit $?
+		;;
 		"*")
 			echo "Error: Invalid operation. Use 'install' ,'remove' or 'list'." >&2
 			exit $return_code_invalid_args
@@ -161,7 +169,7 @@ case $1 in
 		echo $window
 		exit 0
     ;;
-	"list"|"remove"|"install")
+	"list"|"remove"|"install"｜"sotp")
 		apk_process "$1" "$2"
 	;;
 	"write_mode"|"read_mode")
